---
- hosts: all

  tasks:
    - name: Update repository cache and install necessary packages
      apt:
        pkg:
        - nasm
        - build-essential
        - genisoimage
        - bochs
        - bochs-sdl
        update_cache: yes
      become: yes

